version: '3.9'

services:
  # postgres
  postgres:
    env_file:
      - ./config/local.env
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"

  # our backend api application server
  smart-brain-api:
    env_file:
      - ./config/local.env
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm start
    working_dir: /usr/src/smart-brain
    ports:
      - "3000:3000"
    environment:
      DATABASE_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
    volumes:
      - ./:/usr/src/smart-brain

