version: '3.9'

services:
  # postgres
  postgres:
    # env_file:
    #   - ./config/local.env
    # image: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: postgresUser
      # ${POSTGRES_USER}
      POSTGRES_PASSWORD: postgres123
      # ${POSTGRES_PASSWORD}
      POSTGRES_DB: smart-brain
      # ${POSTGRES_DB}
      POSTGRES_HOST: postgresHost
      # ${POSTGRES_HOST}
      DATABASE_URI: postgres://postgresUser:postgres123@localhost:5432/smart-brain
    ports:
      - "5432:5432"

  # our backend api application server
  smart-brain-api:
    env_file:
      - ./config/local.env
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm start
    working_dir: /usr/src/smart-brain
    ports:
      - "3000:3000"
    environment:
      DATABASE_URI: postgres://postgresUser:postgres123@postgresHost:5432/smart-brain
    volumes:
      - ./:/usr/src/smart-brain

